#ifndef CONFIG_H
#define CONFIG_H
#include <gsl/gsl_const_cgsm.h>

// model parameters to edit

#define GMIN 1e2
#define GMAX 1e6
#define U0 4e-13
#define ECMB 2e-9

#define RJET 1e3*GSL_CONST_CGSM_PARSEC
#define LENJET 10*1e3*GSL_CONST_CGSM_PARSEC
#define LUMJET 1e47

#define ETAE 0.1
#define EQUIPART 1

// copy constants from GSL

#define SPEEDC GSL_CONST_CGSM_SPEED_OF_LIGHT
#define PLANCKH GSL_CONST_CGSM_PLANCKS_CONSTANT_H
#define BOLTZMANN  GSL_CONST_CGSM_BOLTZMANN
#define PARSEC GSL_CONST_CGSM_PARSEC
#define ECHARGE GSL_CONST_CGSM_ELECTRON_CHARGE*GSL_CONST_CGSM_SPEED_OF_LIGHT
#define EMASS GSL_CONST_CGSM_MASS_ELECTRON
#define SIGMAT GSL_CONST_CGSM_THOMSON_CROSS_SECTION / (GSL_CONST_CGSM_SPEED_OF_LIGHT*GSL_CONST_CGSM_SPEED_OF_LIGHT)


#endif // !CONFIG_H
